name: Lint OpenAPI Documentation
on:
  pull_request:
    branches:
      - develop
    paths:
      - '**/*.proto'

concurrency:
  group: ci-lint-protobuf-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-changed-directories:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      CHANGED_DIRS: ${{ steps.set-changed-directories.outputs.changed_dirs }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Check changed Golang directories
        id: changed-directories
        uses: tj-actions/changed-files@v44.5.2
        with:
          dir_names: true
          dir_names_max_depth: 1
          files: |
            *-go/**.go
            *-go/go.mod
            *-go/go.sum
          dir_names_exclude_current_dir: true

      - name: Set Changed Directories
        id: set-changed-directories
        env:
          CHANGED_DIRS_COUNT: ${{ steps.changed-directories.outputs.all_changed_files_count }}
        if: ${{ fromJSON(env.CHANGED_DIRS_COUNT) > 0 }}
        run: |
          set -eux
          DATA=$(echo ${{ steps.changed-directories.outputs.all_changed_files }} | jq -Rrjc 'split(" ")' | jq -r 'tostring')
          echo "changed_dirs=$DATA" >> "$GITHUB_OUTPUT"

  lint-protobuf:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    needs: check-changed-directories
    strategy:
      matrix:
        dir: ${{ fromJSON(needs.check-changed-directories.outputs.CHANGED_DIRS) }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Cache Go modules
        uses: actions/cache@v4.0.2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Protolint
        run: go install github.com/yoheimuta/protolint/cmd/protolint@latest

      - name: Run Protolint
        run: protolint lint ./**/*.proto
